name: Run CI Checks

on: push

jobs:
  build-and-lint:
    name: "build & lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 10.x

      - name: Install Deps
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Clean
        run: yarn run clean
  functions-build-and-lint:
    name: "functions: build & lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 10.x

      - name: Install Deps (including root repo deps)
        run: yarn install && cd functions && yarn install

      - name: Build
        run: cd functions && yarn run build

      - name: Lint
        run: cd functions && yarn run lint

      - name: Clean
        run: cd functions && yarn run clean
  functions-test:
    name: "functions: run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 10.x

      - name: Install Deps
        run: cd functions && yarn install

      - name: Run Unit Tests
        run: cd functions && yarn run test
