name: Deploy to Dev

on:
  push:
    branches: [master]

jobs:
  deploy-staging:
    name: Compile Web Apps and Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 10.x

      - name: Install Deps
        run: yarn install

      - name: Build
        env:
          REACT_APP_FACEBOOK_APP_ID: ${{ secrets.DEV_FACEBOOK_API_KEY }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.DEV_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.DEV_FIREBASE_DATABASE_URL }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.DEV_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.DEV_FIREBASE_MESSAGE_SENDER_ID }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_GMAPS_API_KEY: ${{ secrets.DEV_MAPS_API_KEY }} # For the Web Client Project - they have different keys
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.DEV_MUTUAL_AID_MAP_API_KEY }} # For the Map Project - they have different keys
          REACT_APP_DATADOG_APP_ID: ${{ secrets.DEV_DATADOG_APP_ID }}
          REACT_APP_DATADOG_RUM_CLIENT_TOKEN: ${{ secrets.DEV_DATADOG_RUM_CLIENT_TOKEN }}
          REACT_APP_DATADOG_LOGS_CLIENT_TOKEN: ${{ secrets.DEV_DATADOG_LOGS_CLIENT_TOKEN }}
        run: yarn build

      - name: Deploy
        run: |
          yarn run firebase --token "${{secrets.FIREBASE_TOKEN}}" deploy -P reach4help-dev
